from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path


SKILL_DIR = Path(__file__).resolve().parents[1]
PUBLISHER = SKILL_DIR / "scripts" / "publish_ready_issue.py"
BASE_COMMIT = "02b192be4d60ed1f57f27231b7e1d0b31fb5eec2"


def brief_body() -> str:
    return textwrap.dedent(
        """
        > *This was generated by AI during triage.*

        ## Agent Brief

        **Category:** enhancement
        **Summary:** Publish one directly implementable issue.

        **Current behavior:**
        The issue is not available to Ralph.

        **Desired behavior:**
        The issue enters the branch-local Ralph backlog.

        **Key interfaces:**
        - The public publisher command.

        **Acceptance criteria:**
        - [ ] The ready label is applied last.

        **Out of scope:**
        - Pull requests.
        """
    ).strip()


class PublishReadyIssueCliTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp_dir.cleanup)
        self.root = Path(self.temp_dir.name)
        self.repo = self.root / "repo"
        self.repo.mkdir()
        subprocess.run(
            ["git", "init", "--initial-branch=main", str(self.repo)],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        subprocess.run(
            ["git", "-C", str(self.repo), "remote", "add", "origin", "https://github.com/example/project.git"],
            check=True,
        )
        self.outside = self.root / "outside"
        self.outside.mkdir()
        self.brief_file = self.root / "brief.md"
        self.brief_file.write_text(brief_body(), encoding="utf-8")
        self.state_file = self.root / "state.json"
        self.state_file.write_text(
            json.dumps(
                {
                    "number": 42,
                    "title": "Support direct Ralph execution",
                    "body": "## Request\n\nPlease implement this.\n",
                    "state": "OPEN",
                    "labels": ["enhancement", "needs-triage"],
                    "comments": [],
                    "is_pr": False,
                }
            ),
            encoding="utf-8",
        )
        self.event_log = self.root / "events.log"

        self.skill_dir = self.root / "ralph-plan-lqy"
        scripts_dir = self.skill_dir / "scripts"
        scripts_dir.mkdir(parents=True)
        real_adapter = (
            Path(__file__).resolve().parents[3]
            / "lqy-local"
            / "ralph-plan-lqy"
            / "scripts"
            / "producer_adapter.py"
        )
        (scripts_dir / "producer_adapter.py").write_text(
            real_adapter.read_text(encoding="utf-8"),
            encoding="utf-8",
        )
        resolver = scripts_dir / "resolve_spec_git.py"
        resolver.write_text(
            "#!/usr/bin/env python3\n"
            "import json, os, pathlib, sys\n"
            "with pathlib.Path(os.environ['TEST_EVENT_LOG']).open('a') as handle:\n"
            "    handle.write('resolve ' + json.dumps(sys.argv[1:]) + '\\n')\n"
            "branch = sys.argv[sys.argv.index('--branch') + 1] if '--branch' in sys.argv else 'main'\n"
            "base = sys.argv[sys.argv.index('--base-branch') + 1] if '--base-branch' in sys.argv else 'origin/main'\n"
            f"json.dump({{'branch': branch, 'base_branch': base, 'base_commit': '{BASE_COMMIT}'}}, sys.stdout)\n",
            encoding="utf-8",
        )
        resolver.chmod(0o755)
        validator = scripts_dir / "git_contract.py"
        real_validator = (
            Path(__file__).resolve().parents[3]
            / "lqy-local"
            / "ralph-plan-lqy"
            / "scripts"
            / "git_contract.py"
        )
        validator.write_text(real_validator.read_text(encoding="utf-8"), encoding="utf-8")
        provisioner = scripts_dir / "provision_workspace.py"
        provisioner.write_text(
            "#!/usr/bin/env python3\n"
            "import json, os, pathlib, sys\n"
            "with pathlib.Path(os.environ['TEST_EVENT_LOG']).open('a') as handle:\n"
            "    handle.write('provision ' + json.dumps(sys.argv[1:]) + '\\n')\n"
            "if os.environ.get('TEST_FAIL_PROVISION'):\n"
            "    print('PROVISION ERROR: requested failure', file=sys.stderr)\n"
            "    raise SystemExit(3)\n"
            "branch = os.environ.get('TEST_EXPECTED_BRANCH', 'main')\n"
            f"json.dump({{'path': '/tmp/project', 'branch': branch, 'head': '{BASE_COMMIT}', 'upstream': 'origin/' + branch}}, sys.stdout)\n",
            encoding="utf-8",
        )
        provisioner.chmod(0o755)

        bin_dir = self.root / "bin"
        bin_dir.mkdir()
        gh = bin_dir / "gh"
        gh.write_text(
            "#!/usr/bin/env python3\n"
            "import json, os, pathlib, sys\n"
            "args = sys.argv[1:]\n"
            "expected_repo = pathlib.Path(os.environ['TEST_EXPECTED_REPO']).resolve()\n"
            "if pathlib.Path.cwd().resolve() != expected_repo:\n"
            "    print(f'wrong gh cwd: {pathlib.Path.cwd()}', file=sys.stderr)\n"
            "    raise SystemExit(2)\n"
            "state_path = pathlib.Path(os.environ['TEST_STATE_FILE'])\n"
            "state = json.loads(state_path.read_text())\n"
            "log = pathlib.Path(os.environ['TEST_EVENT_LOG'])\n"
            "with log.open('a') as handle:\n"
            "    handle.write('gh ' + json.dumps(args) + '\\n')\n"
            "def save(): state_path.write_text(json.dumps(state))\n"
            "def issue_payload():\n"
            "    body = state['body']\n"
            "    if os.environ.get('TEST_MUTATE_READBACK') and state['comments']:\n"
            "        body += '\\n\\n## Remote change\\n\\nChanged.\\n'\n"
            "    return {**state, 'body': body, 'labels': [{'name': value} for value in state['labels']], "
            "'comments': [{'body': value} for value in state['comments']]}\n"
            "if args[:2] == ['repo', 'view']:\n"
            "    print('example/project')\n"
            "elif args[:1] == ['api']:\n"
            "    print('true' if state['is_pr'] else 'false')\n"
            "elif args[:2] == ['issue', 'view']:\n"
            "    print(json.dumps(issue_payload()))\n"
            "elif args[:2] == ['issue', 'edit']:\n"
            "    if '--body-file' in args:\n"
            "        state['body'] = pathlib.Path(args[args.index('--body-file') + 1]).read_text()\n"
            "    elif '--add-label' in args:\n"
            "        value = args[args.index('--add-label') + 1]\n"
            "        if os.environ.get('TEST_FAIL_READY_LABEL') and value == 'ready-for-agent':\n"
            "            print('requested label failure', file=sys.stderr)\n"
            "            raise SystemExit(1)\n"
            "        if value not in state['labels']: state['labels'].append(value)\n"
            "    elif '--remove-label' in args:\n"
            "        value = args[args.index('--remove-label') + 1]\n"
            "        state['labels'] = [label for label in state['labels'] if label != value]\n"
            "    else:\n"
            "        print('unexpected edit', file=sys.stderr); raise SystemExit(2)\n"
            "    save()\n"
            "elif args[:2] == ['issue', 'comment']:\n"
            "    state['comments'].append(pathlib.Path(args[args.index('--body-file') + 1]).read_text())\n"
            "    save()\n"
            "else:\n"
            "    print(f'unexpected gh argv: {args}', file=sys.stderr); raise SystemExit(2)\n",
            encoding="utf-8",
        )
        gh.chmod(0o755)

        self.env = os.environ.copy()
        self.env["PATH"] = f"{bin_dir}{os.pathsep}{self.env['PATH']}"
        self.env["RALPH_PLAN_SKILL_DIR"] = str(self.skill_dir)
        self.env["TEST_EVENT_LOG"] = str(self.event_log)
        self.env["TEST_STATE_FILE"] = str(self.state_file)
        self.env["TEST_EXPECTED_REPO"] = str(self.repo)

    def publish(self, *extra_args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [
                sys.executable,
                str(PUBLISHER),
                "--repo",
                str(self.repo),
                "--issue",
                "42",
                "--brief-file",
                os.path.relpath(self.brief_file, self.outside),
                *extra_args,
            ],
            text=True,
            capture_output=True,
            env=self.env,
            cwd=self.outside,
        )

    def events(self) -> list[str]:
        return self.event_log.read_text(encoding="utf-8").splitlines() if self.event_log.exists() else []

    def state(self) -> dict[str, object]:
        return json.loads(self.state_file.read_text(encoding="utf-8"))

    def test_provisions_and_validates_body_and_brief_before_applying_ready_label(self) -> None:
        result = self.publish()

        self.assertEqual(0, result.returncode, result.stdout + result.stderr)
        events = self.events()
        operations = []
        for event in events:
            if not event.startswith("gh "):
                operations.append(event.split(" ", 1)[0])
                continue
            argv = json.loads(event.removeprefix("gh "))
            operations.append("api" if argv[0] == "api" else argv[1])
        self.assertEqual(
            ["api", "view", "resolve", "provision", "edit", "comment", "view", "edit", "edit", "view"],
            operations,
        )
        state = self.state()
        self.assertTrue(
            str(state["body"]).rstrip().endswith(
                "## Blocked by\n\n"
                "- None — can start immediately\n\n"
                "## Git\n\n"
                "- Branch: `main`\n"
                "- Base branch: `origin/main`\n"
                f"- Base commit: `{BASE_COMMIT}`"
            )
        )
        self.assertEqual([brief_body()], state["comments"])
        self.assertEqual(["enhancement", "ready-for-agent"], state["labels"])
        self.assertFalse(any("assignee" in event for event in events))
        output = json.loads(result.stdout)
        self.assertEqual("main", output["contract"]["branch"])
        self.assertEqual("/tmp/project", output["workspace"]["path"])

    def test_provision_failure_does_not_modify_or_publish_the_issue(self) -> None:
        original = self.state()
        self.env["TEST_FAIL_PROVISION"] = "1"

        result = self.publish()

        self.assertEqual(3, result.returncode, result.stdout + result.stderr)
        self.assertEqual(original, self.state())
        self.assertFalse(any('"edit"' in event or '"comment"' in event for event in self.events()))

    def test_pull_request_is_rejected_before_contract_resolution_or_provisioning(self) -> None:
        state = self.state()
        state["is_pr"] = True
        self.state_file.write_text(json.dumps(state), encoding="utf-8")

        result = self.publish()

        self.assertEqual(3, result.returncode, result.stdout + result.stderr)
        self.assertIn("is a PR", result.stderr)
        self.assertEqual(1, len(self.events()))
        self.assertTrue(self.events()[0].startswith("gh "))

    def test_issue_requires_exactly_one_category_role_before_publication(self) -> None:
        state = self.state()
        state["labels"] = ["needs-triage"]
        self.state_file.write_text(json.dumps(state), encoding="utf-8")

        result = self.publish()

        self.assertEqual(3, result.returncode, result.stdout + result.stderr)
        self.assertIn("exactly one category role", result.stderr)
        self.assertFalse(any(event.startswith("resolve ") for event in self.events()))

    def test_conflicting_status_roles_stop_before_contract_resolution(self) -> None:
        state = self.state()
        state["labels"] = ["enhancement", "needs-triage", "needs-info"]
        self.state_file.write_text(json.dumps(state), encoding="utf-8")

        result = self.publish()

        self.assertEqual(3, result.returncode, result.stdout + result.stderr)
        self.assertIn("conflicting triage status roles", result.stderr)
        self.assertFalse(any(event.startswith("resolve ") for event in self.events()))

    def test_failed_body_or_brief_readback_leaves_the_issue_unpublished(self) -> None:
        self.env["TEST_MUTATE_READBACK"] = "1"

        result = self.publish()

        self.assertEqual(3, result.returncode, result.stdout + result.stderr)
        self.assertNotIn("ready-for-agent", self.state()["labels"])
        self.assertIn("needs-triage", self.state()["labels"])

    def test_ready_label_failure_restores_the_prior_triage_status(self) -> None:
        self.env["TEST_FAIL_READY_LABEL"] = "1"

        result = self.publish()

        self.assertEqual(1, result.returncode, result.stdout + result.stderr)
        self.assertNotIn("ready-for-agent", self.state()["labels"])
        self.assertIn("needs-triage", self.state()["labels"])

    def test_explicit_branch_and_base_branch_are_forwarded_to_the_shared_resolver(self) -> None:
        self.env["TEST_EXPECTED_BRANCH"] = "feature/triage"

        result = self.publish("--branch", "feature/triage", "--base-branch", "upstream/release")

        self.assertEqual(0, result.returncode, result.stdout + result.stderr)
        resolve_event = next(event for event in self.events() if event.startswith("resolve "))
        resolve_args = json.loads(resolve_event.removeprefix("resolve "))
        self.assertEqual("feature/triage", resolve_args[resolve_args.index("--branch") + 1])
        self.assertEqual("upstream/release", resolve_args[resolve_args.index("--base-branch") + 1])
        self.assertIn("- Branch: `feature/triage`", str(self.state()["body"]))

    def test_skill_and_tracker_seed_route_only_ordinary_issues_through_the_publisher(self) -> None:
        skill = (SKILL_DIR / "SKILL.md").read_text(encoding="utf-8")
        tracker_seed = (
            SKILL_DIR.parent / "setup-matt-pocock-skills-lqy" / "issue-tracker-github.md"
        ).read_text(encoding="utf-8")

        self.assertIn("publish_ready_issue.py", skill)
        self.assertIn("PR 使用 GitHub 原生 head/base", skill)
        self.assertIn("Ralph issue publication 完全忽略 assignees", skill)
        self.assertIn("普通 issue 由 `triage-lqy` 直接建立契约", tracker_seed)
        self.assertIn("Wayfinder 的独立 assignee 约定不受影响", tracker_seed)


if __name__ == "__main__":
    unittest.main()
