#!/bin/sh
set -eu
root="$(git rev-parse --show-toplevel)"
while read -r local_ref local_oid remote_ref remote_oid; do
  case "$local_oid" in ""|*[!0]*) ;; *) continue ;; esac
  "$root/.feature-docs/run" check --ref "$local_oid"
done
