#!/usr/bin/env python3
"""Publish one validated Git-bound triage issue and apply ready last."""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from collections.abc import Sequence
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


READY_LABEL = "ready-for-agent"
CATEGORY_LABELS = ("bug", "enhancement")
PRIOR_STATUS_LABELS = ("needs-triage", "needs-info", "ready-for-human", "wontfix")
AI_DISCLAIMER = "> *This was generated by AI during triage.*"
FULL_SHA_PATTERN = re.compile(r"^[0-9a-fA-F]{40}$")


class PublishError(RuntimeError):
    """Raised when publication would expose an incomplete Ralph issue."""


@dataclass(frozen=True)
class Issue:
    number: int
    title: str
    body: str
    state: str
    labels: frozenset[str]
    comments: tuple[str, ...]


@dataclass(frozen=True)
class WorktreeResult:
    path: str
    branch: str
    head: str
    upstream: str


def run(
    command: list[str],
    *,
    cwd: Path | None = None,
    input_text: str | None = None,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=cwd,
        input=input_text,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def shared_script(name: str) -> Path:
    skill_dir = Path(
        os.environ.get("RALPH_PLAN_SKILL_DIR", Path.home() / ".agents" / "skills" / "ralph-plan-lqy")
    )
    script = skill_dir / "scripts" / name
    if not script.is_file():
        raise PublishError(f"required ralph-plan-lqy script is not installed: {script}")
    return script


def command_json(command: list[str], *, input_text: str | None = None) -> dict[str, Any]:
    result = run(command, input_text=input_text)
    if result.returncode == 3:
        raise PublishError(result.stderr.strip() or result.stdout.strip() or f"{' '.join(command)} failed")
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or f"exit {result.returncode}"
        raise OSError(f"{' '.join(command)} failed: {detail}")
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise OSError(f"{' '.join(command)} returned invalid JSON") from exc
    if not isinstance(payload, dict):
        raise OSError(f"{' '.join(command)} returned a non-object JSON value")
    return payload


def contract_from_payload(payload: dict[str, Any], *, source: str) -> dict[str, str]:
    fields = ("branch", "base_branch", "base_commit")
    missing = [field for field in fields if field not in payload]
    if missing:
        raise OSError(f"{source} returned incomplete JSON; missing: {', '.join(missing)}")
    if not all(isinstance(payload[field], str) and payload[field] for field in fields):
        raise OSError(f"{source} returned invalid Git contract field types")
    if FULL_SHA_PATTERN.fullmatch(payload["base_commit"]) is None:
        raise OSError(f"{source} returned an invalid base commit")
    return {field: payload[field] for field in fields}


def resolve_contract(repo: Path, branch: str | None, base_branch: str | None) -> dict[str, str]:
    command = [sys.executable, str(shared_script("resolve_spec_git.py")), "--repo", str(repo)]
    if branch is not None:
        command.extend(["--branch", branch])
    if base_branch is not None:
        command.extend(["--base-branch", base_branch])
    return contract_from_payload(command_json(command), source="shared Git contract resolver")


def validate_contract(body: str) -> dict[str, str]:
    payload = command_json(
        [sys.executable, str(shared_script("git_contract.py")), "--require-unique"],
        input_text=body,
    )
    return contract_from_payload(payload, source="shared Git contract validator")


def provision_workspace(
    repo: Path,
    body: str,
    *,
    expected_branch: str,
) -> WorktreeResult:
    command = [sys.executable, str(shared_script("provision_workspace.py")), "--repo", str(repo)]
    payload = command_json(command, input_text=body)
    fields = ("path", "branch", "head", "upstream")
    missing = [field for field in fields if field not in payload]
    if missing:
        raise OSError(f"workspace provisioner returned incomplete JSON; missing: {', '.join(missing)}")
    if not all(isinstance(payload[field], str) and payload[field] for field in fields):
        raise OSError("workspace provisioner returned invalid WorktreeResult field types")
    if payload["branch"] != expected_branch:
        raise OSError(
            f"workspace provisioner returned branch `{payload['branch']}`, expected `{expected_branch}`"
        )
    if not Path(payload["path"]).is_absolute():
        raise OSError("workspace provisioner returned a non-absolute worktree path")
    if FULL_SHA_PATTERN.fullmatch(payload["head"]) is None:
        raise OSError("workspace provisioner returned an invalid HEAD commit")
    return WorktreeResult(**{field: payload[field] for field in fields})


def gh(repo: Path, *args: str) -> str:
    result = run(["gh", *args], cwd=repo)
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or f"exit {result.returncode}"
        raise OSError(f"gh {' '.join(args)} failed: {detail}")
    return result.stdout


def reject_pull_request(repo: Path, number: int) -> None:
    output = gh(
        repo,
        "api",
        f"repos/{{owner}}/{{repo}}/issues/{number}",
        "--jq",
        'has("pull_request")',
    ).strip()
    if output == "true":
        raise PublishError(f"#{number} is a PR; triage PRs do not enter the Ralph issue backlog")
    if output != "false":
        raise OSError(f"gh api returned an unexpected PR marker for #{number}: {output or '<empty>'}")


def issue_from_json(payload: dict[str, Any]) -> Issue:
    try:
        labels = frozenset(
            str(label["name"])
            for label in payload.get("labels", [])
            if isinstance(label, dict) and label.get("name")
        )
        comments = tuple(
            str(comment["body"])
            for comment in payload.get("comments", [])
            if isinstance(comment, dict) and "body" in comment
        )
        return Issue(
            number=int(payload["number"]),
            title=str(payload.get("title") or ""),
            body=str(payload.get("body") or ""),
            state=str(payload.get("state") or ""),
            labels=labels,
            comments=comments,
        )
    except (KeyError, TypeError, ValueError) as exc:
        raise OSError("gh issue view returned malformed issue JSON") from exc


def view_issue(repo: Path, number: int) -> Issue:
    output = gh(
        repo,
        "issue",
        "view",
        str(number),
        "--json",
        "number,title,body,state,labels,comments",
    )
    try:
        payload = json.loads(output)
    except json.JSONDecodeError as exc:
        raise OSError(f"gh issue view {number} returned invalid JSON") from exc
    if not isinstance(payload, dict):
        raise OSError(f"gh issue view {number} returned a non-object JSON value")
    return issue_from_json(payload)


def validate_brief(brief: str) -> str:
    if not brief.startswith(AI_DISCLAIMER):
        raise PublishError(f"agent brief must start with `{AI_DISCLAIMER}`")
    if "## Agent Brief" not in brief:
        raise PublishError("agent brief is missing `## Agent Brief`")
    category = re.search(r"^\*\*Category:\*\*\s*(bug|enhancement)\s*$", brief, flags=re.MULTILINE)
    if category is None:
        raise PublishError("agent brief must declare `**Category:** bug` or `**Category:** enhancement`")
    return category.group(1)


def validate_roles(issue: Issue, *, brief_category: str) -> None:
    categories = tuple(label for label in CATEGORY_LABELS if label in issue.labels)
    if len(categories) != 1:
        raise PublishError(
            f"issue #{issue.number} must have exactly one category role (`bug` or `enhancement`)"
        )
    if categories[0] != brief_category:
        raise PublishError(
            f"issue #{issue.number} category role `{categories[0]}` does not match agent brief `{brief_category}`"
        )
    statuses = tuple(label for label in (*PRIOR_STATUS_LABELS, READY_LABEL) if label in issue.labels)
    if len(statuses) > 1:
        raise PublishError(
            f"issue #{issue.number} has conflicting triage status roles: {', '.join(f'`{label}`' for label in statuses)}"
        )


def render_contract(contract: dict[str, str]) -> str:
    return (
        "## Git\n\n"
        f"- Branch: `{contract['branch']}`\n"
        f"- Base branch: `{contract['base_branch']}`\n"
        f"- Base commit: `{contract['base_commit']}`"
    )


def render_issue_body(body: str, contract: dict[str, str]) -> str:
    headings = re.findall(r"^##\s+([^\n]+?)\s*$", body, flags=re.MULTILINE)
    if "Git" in headings or "Blocked by" in headings:
        raise PublishError("issue body already contains a reserved `## Git` or `## Blocked by` section")
    prefix = body.rstrip()
    if prefix:
        prefix += "\n\n"
    return (
        f"{prefix}## Blocked by\n\n"
        "- None — can start immediately\n\n"
        f"{render_contract(contract)}\n"
    )


def validate_prepared_issue(issue: Issue, *, body: str, brief: str) -> None:
    if issue.state.upper() != "OPEN":
        raise PublishError(f"issue #{issue.number} is {issue.state or 'not open'}")
    if issue.body.rstrip("\n") != body.rstrip("\n"):
        raise PublishError(f"issue #{issue.number} body changed during publication")
    if brief.rstrip("\n") not in {comment.rstrip("\n") for comment in issue.comments}:
        raise PublishError(f"issue #{issue.number} agent brief was not retained")
    if READY_LABEL in issue.labels:
        raise PublishError(f"issue #{issue.number} received `{READY_LABEL}` before validation")
    validate_contract(issue.body)


def restore_status_labels(repo: Path, number: int, labels: Sequence[str]) -> list[str]:
    errors: list[str] = []
    for label in labels:
        try:
            gh(repo, "issue", "edit", str(number), "--add-label", label)
        except OSError as exc:
            errors.append(str(exc))
    return errors


def apply_ready_label(repo: Path, issue: Issue) -> tuple[str, ...]:
    removed = tuple(label for label in PRIOR_STATUS_LABELS if label in issue.labels)
    completed_removals: list[str] = []
    try:
        for label in removed:
            gh(repo, "issue", "edit", str(issue.number), "--remove-label", label)
            completed_removals.append(label)
        gh(repo, "issue", "edit", str(issue.number), "--add-label", READY_LABEL)
    except OSError as exc:
        rollback_errors = restore_status_labels(repo, issue.number, completed_removals)
        if rollback_errors:
            raise OSError(f"ready label failed: {exc}; status rollback incomplete: {'; '.join(rollback_errors)}") from exc
        raise OSError(f"ready label failed; prior status labels restored: {exc}") from exc
    return removed


def rollback_ready_label(repo: Path, issue: Issue, removed: Sequence[str]) -> list[str]:
    errors: list[str] = []
    try:
        gh(repo, "issue", "edit", str(issue.number), "--remove-label", READY_LABEL)
    except OSError as exc:
        errors.append(str(exc))
    errors.extend(restore_status_labels(repo, issue.number, removed))
    return errors


def publish(
    repo: Path,
    number: int,
    brief_file: Path,
    *,
    branch: str | None,
    base_branch: str | None,
) -> dict[str, Any]:
    reject_pull_request(repo, number)
    issue = view_issue(repo, number)
    if issue.state.upper() != "OPEN":
        raise PublishError(f"issue #{number} is {issue.state or 'not open'}")
    if READY_LABEL in issue.labels:
        raise PublishError(f"issue #{number} already has `{READY_LABEL}`")
    if re.match(r"^\s*Spec\s*:", issue.title, flags=re.IGNORECASE):
        raise PublishError(f"issue #{number} is a parent spec, not a direct triage issue")

    brief = brief_file.read_text(encoding="utf-8")
    brief_category = validate_brief(brief)
    validate_roles(issue, brief_category=brief_category)
    contract = resolve_contract(repo, branch, base_branch)
    body = render_issue_body(issue.body, contract)
    if validate_contract(body) != contract:
        raise OSError("shared Git contract validator changed the resolved contract")
    workspace = provision_workspace(
        repo,
        body,
        expected_branch=contract["branch"],
    )

    with tempfile.TemporaryDirectory(prefix="triage-lqy-") as temporary:
        body_file = Path(temporary) / "issue.md"
        body_file.write_text(body, encoding="utf-8")
        gh(repo, "issue", "edit", str(number), "--body-file", str(body_file))
    gh(repo, "issue", "comment", str(number), "--body-file", str(brief_file))

    prepared = view_issue(repo, number)
    validate_prepared_issue(prepared, body=body, brief=brief)
    removed = apply_ready_label(repo, prepared)
    try:
        published = view_issue(repo, number)
        if published.state.upper() != "OPEN" or READY_LABEL not in published.labels:
            raise PublishError(f"issue #{number} did not retain the validated `{READY_LABEL}` state")
        if any(label in published.labels for label in PRIOR_STATUS_LABELS):
            raise PublishError(f"issue #{number} retained a conflicting triage status label")
        if published.body.rstrip("\n") != body.rstrip("\n"):
            raise PublishError(f"issue #{number} body changed after ready publication")
        if brief.rstrip("\n") not in {comment.rstrip("\n") for comment in published.comments}:
            raise PublishError(f"issue #{number} agent brief changed after ready publication")
    except (PublishError, OSError) as exc:
        rollback_errors = rollback_ready_label(repo, prepared, removed)
        if rollback_errors:
            raise OSError(f"ready readback failed: {exc}; rollback incomplete: {'; '.join(rollback_errors)}") from exc
        raise

    return {
        "contract": contract,
        "issue": number,
        "label": READY_LABEL,
        "workspace": asdict(workspace),
    }


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Publish one Git-bound triage issue with label-last semantics.")
    parser.add_argument("--repo", default=".", type=Path, help="Any path inside the target Git repository.")
    parser.add_argument("--issue", required=True, type=int, help="Open GitHub issue number to publish.")
    parser.add_argument("--brief-file", required=True, type=Path, help="Complete triage agent brief comment.")
    parser.add_argument("--branch", help="Explicit target branch; defaults to the remote default branch.")
    parser.add_argument("--base-branch", help="Explicit remote base ref, for example `origin/release`.")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    try:
        result = publish(
            args.repo,
            args.issue,
            args.brief_file,
            branch=args.branch,
            base_branch=args.base_branch,
        )
    except PublishError as exc:
        print(f"PUBLISH ERROR: {exc}", file=sys.stderr)
        return 3
    except OSError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
