#!/usr/bin/env python3
"""Publish one validated Git-bound triage issue and apply ready last."""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import re
import sys
import tempfile
from collections.abc import Sequence
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast


if TYPE_CHECKING:
    from producer_adapter import GitContract, ProducerToolAdapter


READY_LABEL = "ready-for-agent"
CATEGORY_LABELS = ("bug", "enhancement")
PRIOR_STATUS_LABELS = ("needs-triage", "needs-info", "ready-for-human", "wontfix")
AI_DISCLAIMER = "> *This was generated by AI during triage.*"


class PublishError(RuntimeError):
    """Raised when publication would expose an incomplete Ralph issue."""


@dataclass(frozen=True)
class Issue:
    number: int
    title: str
    body: str
    state: str
    labels: frozenset[str]
    comments: tuple[str, ...]


def load_producer_adapter(repo: Path) -> ProducerToolAdapter:
    skill_dir = Path(
        os.environ.get("RALPH_PLAN_SKILL_DIR", Path.home() / ".agents" / "skills" / "ralph-plan-lqy")
    )
    adapter_path = skill_dir / "scripts" / "producer_adapter.py"
    if not adapter_path.is_file():
        raise PublishError(f"shared producer adapter is not installed: {adapter_path}")
    spec = importlib.util.spec_from_file_location("ralph_plan_producer_adapter", adapter_path)
    if spec is None or spec.loader is None:
        raise PublishError(f"cannot load shared producer adapter: {adapter_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return cast("ProducerToolAdapter", module.ProducerToolAdapter(repo, skill_dir=skill_dir))


def reject_pull_request(tools: ProducerToolAdapter, number: int) -> None:
    output = tools.gh(
        "api",
        f"repos/{{owner}}/{{repo}}/issues/{number}",
        "--jq",
        'has("pull_request")',
    ).strip()
    if output == "true":
        raise PublishError(f"#{number} is a PR; triage PRs do not enter the Ralph issue backlog")
    if output != "false":
        raise OSError(f"gh api returned an unexpected PR marker for #{number}: {output or '<empty>'}")


def issue_from_json(payload: dict[str, Any]) -> Issue:
    try:
        labels = frozenset(
            str(label["name"])
            for label in payload.get("labels", [])
            if isinstance(label, dict) and label.get("name")
        )
        comments = tuple(
            str(comment["body"])
            for comment in payload.get("comments", [])
            if isinstance(comment, dict) and "body" in comment
        )
        return Issue(
            number=int(payload["number"]),
            title=str(payload.get("title") or ""),
            body=str(payload.get("body") or ""),
            state=str(payload.get("state") or ""),
            labels=labels,
            comments=comments,
        )
    except (KeyError, TypeError, ValueError) as exc:
        raise OSError("gh issue view returned malformed issue JSON") from exc


def view_issue(tools: ProducerToolAdapter, number: int) -> Issue:
    output = tools.gh(
        "issue",
        "view",
        str(number),
        "--json",
        "number,title,body,state,labels,comments",
    )
    try:
        payload = json.loads(output)
    except json.JSONDecodeError as exc:
        raise OSError(f"gh issue view {number} returned invalid JSON") from exc
    if not isinstance(payload, dict):
        raise OSError(f"gh issue view {number} returned a non-object JSON value")
    return issue_from_json(payload)


def validate_brief(brief: str) -> str:
    if not brief.startswith(AI_DISCLAIMER):
        raise PublishError(f"agent brief must start with `{AI_DISCLAIMER}`")
    if "## Agent Brief" not in brief:
        raise PublishError("agent brief is missing `## Agent Brief`")
    category = re.search(r"^\*\*Category:\*\*\s*(bug|enhancement)\s*$", brief, flags=re.MULTILINE)
    if category is None:
        raise PublishError("agent brief must declare `**Category:** bug` or `**Category:** enhancement`")
    return category.group(1)


def validate_roles(issue: Issue, *, brief_category: str) -> None:
    categories = tuple(label for label in CATEGORY_LABELS if label in issue.labels)
    if len(categories) != 1:
        raise PublishError(
            f"issue #{issue.number} must have exactly one category role (`bug` or `enhancement`)"
        )
    if categories[0] != brief_category:
        raise PublishError(
            f"issue #{issue.number} category role `{categories[0]}` does not match agent brief `{brief_category}`"
        )
    statuses = tuple(label for label in (*PRIOR_STATUS_LABELS, READY_LABEL) if label in issue.labels)
    if len(statuses) > 1:
        raise PublishError(
            f"issue #{issue.number} has conflicting triage status roles: {', '.join(f'`{label}`' for label in statuses)}"
        )


def render_contract(contract: GitContract) -> str:
    return (
        "## Git\n\n"
        f"- Branch: `{contract.branch}`\n"
        f"- Base branch: `{contract.base_branch}`\n"
        f"- Base commit: `{contract.base_commit}`"
    )


def render_issue_body(body: str, contract: GitContract) -> str:
    headings = re.findall(r"^##\s+([^\n]+?)\s*$", body, flags=re.MULTILINE)
    if "Git" in headings or "Blocked by" in headings:
        raise PublishError("issue body already contains a reserved `## Git` or `## Blocked by` section")
    prefix = body.rstrip()
    if prefix:
        prefix += "\n\n"
    return (
        f"{prefix}## Blocked by\n\n"
        "- None — can start immediately\n\n"
        f"{render_contract(contract)}\n"
    )


def validate_prepared_issue(
    tools: ProducerToolAdapter,
    issue: Issue,
    *,
    body: str,
    brief: str,
) -> None:
    if issue.state.upper() != "OPEN":
        raise PublishError(f"issue #{issue.number} is {issue.state or 'not open'}")
    if issue.body.rstrip("\n") != body.rstrip("\n"):
        raise PublishError(f"issue #{issue.number} body changed during publication")
    if brief.rstrip("\n") not in {comment.rstrip("\n") for comment in issue.comments}:
        raise PublishError(f"issue #{issue.number} agent brief was not retained")
    if READY_LABEL in issue.labels:
        raise PublishError(f"issue #{issue.number} received `{READY_LABEL}` before validation")
    tools.validate_git_contract(issue.body)


def restore_status_labels(
    tools: ProducerToolAdapter,
    number: int,
    labels: Sequence[str],
) -> list[str]:
    errors: list[str] = []
    for label in labels:
        try:
            tools.gh("issue", "edit", str(number), "--add-label", label)
        except OSError as exc:
            errors.append(str(exc))
    return errors


def apply_ready_label(tools: ProducerToolAdapter, issue: Issue) -> tuple[str, ...]:
    removed = tuple(label for label in PRIOR_STATUS_LABELS if label in issue.labels)
    completed_removals: list[str] = []
    try:
        for label in removed:
            tools.gh("issue", "edit", str(issue.number), "--remove-label", label)
            completed_removals.append(label)
        tools.gh("issue", "edit", str(issue.number), "--add-label", READY_LABEL)
    except OSError as exc:
        rollback_errors = restore_status_labels(tools, issue.number, completed_removals)
        if rollback_errors:
            raise OSError(f"ready label failed: {exc}; status rollback incomplete: {'; '.join(rollback_errors)}") from exc
        raise OSError(f"ready label failed; prior status labels restored: {exc}") from exc
    return removed


def rollback_ready_label(
    tools: ProducerToolAdapter,
    issue: Issue,
    removed: Sequence[str],
) -> list[str]:
    errors: list[str] = []
    try:
        tools.gh("issue", "edit", str(issue.number), "--remove-label", READY_LABEL)
    except OSError as exc:
        errors.append(str(exc))
    errors.extend(restore_status_labels(tools, issue.number, removed))
    return errors


def publish(
    repo: Path,
    number: int,
    brief_file: Path,
    *,
    branch: str | None,
    base_branch: str | None,
) -> dict[str, Any]:
    tools = load_producer_adapter(repo)
    reject_pull_request(tools, number)
    issue = view_issue(tools, number)
    if issue.state.upper() != "OPEN":
        raise PublishError(f"issue #{number} is {issue.state or 'not open'}")
    if READY_LABEL in issue.labels:
        raise PublishError(f"issue #{number} already has `{READY_LABEL}`")
    if re.match(r"^\s*Spec\s*:", issue.title, flags=re.IGNORECASE):
        raise PublishError(f"issue #{number} is a parent spec, not a direct triage issue")

    brief_file = brief_file.expanduser().resolve()
    brief = brief_file.read_text(encoding="utf-8")
    brief_category = validate_brief(brief)
    validate_roles(issue, brief_category=brief_category)
    contract = tools.resolve_git_contract(branch, base_branch)
    body = render_issue_body(issue.body, contract)
    if tools.validate_git_contract(body) != contract:
        raise OSError("shared Git contract validator changed the resolved contract")
    workspace = tools.provision_workspace(body, expected_branch=contract.branch)

    with tempfile.TemporaryDirectory(prefix="triage-lqy-") as temporary:
        body_file = Path(temporary) / "issue.md"
        body_file.write_text(body, encoding="utf-8")
        tools.gh("issue", "edit", str(number), "--body-file", str(body_file))
    tools.gh("issue", "comment", str(number), "--body-file", str(brief_file))

    prepared = view_issue(tools, number)
    validate_prepared_issue(tools, prepared, body=body, brief=brief)
    removed = apply_ready_label(tools, prepared)
    try:
        published = view_issue(tools, number)
        if published.state.upper() != "OPEN" or READY_LABEL not in published.labels:
            raise PublishError(f"issue #{number} did not retain the validated `{READY_LABEL}` state")
        if any(label in published.labels for label in PRIOR_STATUS_LABELS):
            raise PublishError(f"issue #{number} retained a conflicting triage status label")
        if published.body.rstrip("\n") != body.rstrip("\n"):
            raise PublishError(f"issue #{number} body changed after ready publication")
        if brief.rstrip("\n") not in {comment.rstrip("\n") for comment in published.comments}:
            raise PublishError(f"issue #{number} agent brief changed after ready publication")
    except (PublishError, OSError) as exc:
        rollback_errors = rollback_ready_label(tools, prepared, removed)
        if rollback_errors:
            raise OSError(
                f"ready readback failed: {exc}; rollback incomplete: {'; '.join(rollback_errors)}"
            ) from exc
        raise

    return {
        "contract": asdict(contract),
        "issue": number,
        "label": READY_LABEL,
        "workspace": asdict(workspace),
    }


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Publish one Git-bound triage issue with label-last semantics.")
    parser.add_argument("--repo", default=".", type=Path, help="Any path inside the target Git repository.")
    parser.add_argument("--issue", required=True, type=int, help="Open GitHub issue number to publish.")
    parser.add_argument("--brief-file", required=True, type=Path, help="Complete triage agent brief comment.")
    parser.add_argument(
        "--branch",
        help="Explicit target branch; defaults to the branch attached to --repo, or the remote default when detached.",
    )
    parser.add_argument("--base-branch", help="Explicit remote base ref, for example `origin/release`.")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    try:
        result = publish(
            args.repo,
            args.issue,
            args.brief_file,
            branch=args.branch,
            base_branch=args.base_branch,
        )
    except (PublishError, ValueError) as exc:
        print(f"PUBLISH ERROR: {exc}", file=sys.stderr)
        return 3
    except OSError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
